***In this notebook, we will be covering about Numpy Indexing and Selection***

In [2]:
import numpy as np

In [4]:
arr = np.arange(0,11,1)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[8]

8

In [16]:
arr[1:5]

array([1, 2, 3, 4])

In [18]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [20]:
arr[:5]

array([0, 1, 2, 3, 4])

In [22]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

***Broadcasting Re-assignment***

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr[0:5] = 100

In [28]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [33]:
arr = np.arange(0,11)

In [35]:
slice_of_arr = arr[0:5]

In [37]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
slice_of_arr[:] = 99

In [43]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [45]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [47]:
arr_copy = arr.copy()

In [49]:
arr_copy[:] = 100

In [51]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [53]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

***Grabing elements in 2d array***

In [57]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [59]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
arr_2d.shape

(3, 3)

In [64]:
arr_2d[0]

array([ 5, 10, 15])

In [66]:
arr_2d[2]

array([35, 40, 45])

In [78]:
arr_2d[1][1]

25

In [82]:
arr_2d[0,2]

15

***Slicing a Subset of n-dimentional array***

In [85]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [89]:
arr_2d[1][1:]

array([25, 30])

In [107]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

***Conditional Selection***

In [112]:
arr = np.arange(0,11)

In [114]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [120]:
bool_arr = arr > 4

In [122]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [124]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [118]:
# In a simple One step
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])