### ***Numpy Arrays***

In [2]:
import numpy as np

### ***Creating Numpy Array Using Standard Python List:***

In [4]:
my_list = [1,2,3]

In [5]:
type(my_list)

list

In [6]:
np.array(my_list)

array([1, 2, 3])

Keep in mind this doesn't effect the original my_list as a whole. We have to reaasign it to any variable ex:- myarr

In [8]:
myarr = np.array(my_list)

In [9]:
myarr

array([1, 2, 3])

In [10]:
type(myarr)

numpy.ndarray

***Creating a N-dimentional array***

In [12]:
my_matrix = [[1,2,3],[4,5,6], [7,8,9]]

In [13]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

***my_matrix now just look's like a standard python nested list***

In [15]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### ***Built-in Functions of Numpy Array:***

In [17]:
np.arange(0,10)                          # Numpy's arrange function is equivalent to Python's Built in Range Function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# help(np.arange)    --------> we can use help(any function) to read the doc-string of that function

In [19]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

***Note: That the zeros here are floating point numbers***

In [22]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.linspace(0,10,3)          # This function returns a evenly spaced numbers over a specified interval

array([ 0.,  5., 10.])

In [26]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
len(np.linspace(0,10,11))

11

In [28]:
np.eye(5)           #Create a identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

***Numpy Random Library:***

In [30]:
np.random.rand(1)

array([0.79678417])

In [31]:
np.random.rand(5,2)

array([[0.96805784, 0.65022211],
       [0.66523505, 0.51994583],
       [0.97064251, 0.4221929 ],
       [0.79865678, 0.18209801],
       [0.45176051, 0.49253432]])

In [32]:
np.random.randn(10)

array([-0.8602807 ,  0.91471749,  0.31401291,  1.29368007,  0.27999735,
        0.86888176,  0.02568879, -0.64347109, -1.64851487,  0.1700502 ])

In [33]:
np.random.randn(2,3)

array([[-0.90761196, -0.63928043, -0.49680698],
       [-0.44899535,  1.29595018,  1.19911244]])

In [34]:
np.random.randint(0,101)

54

In [35]:
np.random.randint(0,101,5)

array([38, 65, 73, 68, 57])

In [36]:
np.random.randint(0,101,(4,5))

array([[62, 10,  9, 36, 33],
       [95, 70, 34,  5, 23],
       [43, 62, 29,  7, 57],
       [35, 50, 91, 78, 95]])

In [37]:
# Setting a seed to get a particular set of random numbers

np.random.seed(42)        # 42 is a common orbitary number but you can use any number for seed
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

***Make sure you're seed is in the same cell as the code***

In [39]:
arr = np.arange(0,25)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [43]:
randarr = np.random.randint(0,101,10)

In [45]:
randarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [47]:
randarr.max()   # To see the maximum interger in an arr

99

In [49]:
randarr.min()   # Tp see the minimum integer in an arr

2

In [51]:
randarr.argmax()  # To know the index position of an maximum integer

5

In [53]:
randarr.argmin()  # To know the index position of an minimum integer

7

In [55]:
randarr.dtype   # To know the datatype of an array

dtype('int32')

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
arr.shape

(25,)

***Why (25,nothing)? : <br>***
***Because (25,) represents whether the data contained as a long format of the array horizontally or vertically. <br>***
***If it's (25,) then there are no columns and it is a list of numbers <br>***
***If it's (25,1) then there are one long vertical format numbers***

In [62]:
arr = arr.reshape(5,5)

In [64]:
arr.shape

(5, 5)

In [66]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [68]:
arr.reshape(25,1).shape

(25, 1)